### PR TITLE
Update cold_ammonia model

### PR DESCRIPTION
**Pull request by jpinedaf**
I update both cubefit and update_NH3_momento0 with the new cold_ammonia model from pyspeckit. 
I tested it on B59, and it should work!

### CODE REVIEW

**Comment by jpinedaf** [comment]
@ElettraR address #125

**Comment by jpinedaf** [comment]
we are holding up on this until the `ammonia_cold` function/modelling has been fully tested

**Comment by low-sky** [comment]
Next couple of days.  I think you know part why last week was a wash for me.

**Comment by jpinedaf** [comment]
indeed... that is why i didn't have a lot of progress this week neither

**Pull request merged**
