### PR TITLE
Analysis of binned regions

### PR DESCRIPTION
**Pull request by Nestak2**
This is the code created so far during the summer internship at UofA. It contains code that bins spectra of regions with similar properties (temperature, brightnes, density), averages the spectra, and than analyses them via graphs.

### CODE REVIEW

**Comment by jpinedaf** [comment]
Great work! should we set it up as a different repo within the GBTAmmoniaSurvey project? Since it mostly uses the GAS infrastructure for a stand-alone analysis. What do you think? @low-sky @keflavich @rfriesen

**Comment by rfriesen** [comment]
Agreed, looks great! The repo suggestion makes sense to me as well.

**Comment by Nestak2** [comment]
I am glad to read, that it satisfies you guys. I will "polish" the code contribution in the next 3 weeks - nevertheless, changes will be about the style of the code, the functionality will remain the same. This upload was more of a test, giving you a glimpse how it roughly would do, before reaching its final look.
I will stay tuned what suggestions and wishes you guys, and Eric Rosolowsky, will give me for implementing.Thanks for having me here, cheers! 

    rfriesen <notifications@github.com> schrieb am 7:11 Donnerstag, 30.Juni 2016:
 

 Agreed, looks great! The repo suggestion makes sense to me as well. —

**Comment by low-sky** [comment]
We definitely need to organize this.  We can either put in an `analysis` submodule to GAS or create a new repository.  Inside GAS is simpler, but a separate repository could handle more methods.

**Comment by low-sky** [comment]
We will pull this into a separate repository for analysis.

**Comment by jpinedaf** [comment]
I like that approach better! Thanks :)
On Sa., 9. Juli 2016 at 00:24, Erik Rosolowsky <notifications@github.com>
wrote:

> We will pull this into a separate repository for analysis.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/GBTAmmoniaSurvey/GAS/pull/136#issuecomment-231487216>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGOgWnBf_NFamZ4qR-6jUF0SFWI3JlDtks5qTs4tgaJpZM4JBpQD>
> .
>
-- 
------------------------------
Dr. Jaime E Pineda                  Phone: +49 89 300003610
Max-Planck-Institut für extraterrestrische Physik
Giessenbachstrasse 1
85748 Garching
Germany

**Pull request closed without merging**
