### PR TITLE
Remove cube edges, see issue #76

### PR DESCRIPTION
**Pull request by jpinedaf**
-create function trim_edge_cube(), which is called after the baseline is
 removed. Default behaviour is to remove edges, but it can be controlled
 by trim_edge keyword:
 `baseline( file_in, file_out, trim_edge=True)`
.

### CODE REVIEW

**Comment by jpinedaf** [comment]
@keflavich @low-sky @rfriesen I wonder if there is a more efficient or elegant way to create the mask to blank than doing 
```python
cube[~ (mask*erosion(mask_2d,disk(3)))]=np.nan
```

**Comment by keflavich** [comment]
`mask&erosion(...)`, for one.  But usually you want to use `cube.with_mask`....

**Comment by keflavich** [comment]
I'd do something like this:
```
mask2d = cube.mask.include().max(axis=0) # find all valid pixels in 2D
# maybe these are 2-liners as you had before...
mask2d[0,:] = mask2d[-1,:] = False
mask2d[:,0] = mask2d[:,-1] = False
mask2d &= erosion(mask2d, disk(3))
cube_masked = cube.with_mask(mask2d)
cube_masked_cropped = cube_masked.minimal_subcube()
```

**Comment by keflavich** [comment]
After looking at https://github.com/GBTAmmoniaSurvey/GAS/issues/76, I realize you want to save these to disk.  Note that the cube will replace all masked pixels with `cube.fill_value`, which can be set using `with_fill_value`, when writing.  Technically, I think my solution is no more efficient, but this might be slightly more efficient:

```
mask2d = cube.mask.include().max(axis=0) # find all valid pixels in 2D
# maybe these are 2-liners as you had before...
mask2d[0,:] = mask2d[-1,:] = False
mask2d[:,0] = mask2d[:,-1] = False
cube_masked = cube.with_mask(mask2d).with_mask(erosion(mask2d, disk(3)))
# crop cube to remove all unnecessary edge regions
cube_masked_cropped = cube_masked.minimal_subcube()
```

but any performance enhancement at this level is negligible...

**Comment by jpinedaf** [comment]
This is interesting, however, we are not using `Spectral_Cube` in this part of the code mostly because the baseline removal is not implemented in `Spectral_Cube`. 

I just modified the code to include some of these suggestions, however, I don't see the use for this line
`mask2d &= erosion(mask2d, disk(3))` instead of `mask2d = erosion(mask2d, disk(3))`.... I guess it is `mask &= erosion(mask2d, disk(3))` :+1:

**Comment by keflavich** [comment]
OK, makes sense.  But, you might want to do this cropping/edge removal before you do anything else, including baseline subtraction.

**Comment by jpinedaf** [comment]
Yes, you are right, the trimming is now done before baseline removal. This should be ready for merging

**Pull request merged**
