### PR TITLE
Stacking and Voronoi binning

### PR DESCRIPTION
**Pull request by low-sky**
This PR implements stacking and Voronoi binning to bring up signal-to-noise of one line given prior information about another line.  As part of the preparation for this work, I also updated the requirements of the GAS package to be consistent with recent releases of other packages.

I've posted a demo of the code for the B59 data in [this gist](https://gist.github.com/low-sky/a88fc74a6693ca675fe9).  

Here are some results for two different Voronoi binning approaches including signal-to-noise based aggregation.  Color scale is HC5N and the contours are ammonia (1,1) with a stack on the ammonia velocity centroid.  
b59_hc5n_snagg
and for flux based aggregation
b59_hc5n_fluxagg

Next up: better centroids for priors to fits.  I envision we should improve centroids, fit, and then use fit centroids for stacking.

### CODE REVIEW

**Comment by low-sky** [comment]
@jpinedaf @keflavich -- Okay to merge?

**Comment by keflavich** [comment]
I haven't had / don't have time for a full review now; fine by me.  I would like to understand this, though - perhaps a topic for next week.5?

**Comment by jpinedaf** [comment]
It looks good... but I have not been able to really test this. I agree with Adam, we should discuss this while you are in Garching :)

**Comment by jpinedaf** [comment]
I'm trying the code on B18, just to check. 

I followed the example in the gist posted. I think that these two lines should be modified:
https://gist.github.com/low-sky/a88fc74a6693ca675fe9#file-stackcheck-py-L25
and 
https://gist.github.com/low-sky/a88fc74a6693ca675fe9#file-stackcheck-py-L37
into 
```python
SNlabels, SNmap = gb.VoronoiBin(mom0,rms,threshold=0,TargetValue=10)
SNlabels, SNmap = gb.VoronoiBin(mom0,rms,threshold=0,TargetValue=10,aggregator = Fluxx)
```

Also, the moment-0 is not really well calculated in 
https://gist.github.com/low-sky/a88fc74a6693ca675fe9#file-stackcheck-py-L27
it should be this instead (similar in line 40):
```python
hc5n_moment = output[411:435].moment(0)
```

But, I think that what you are plotting is actually the labels and not the integrated intensity. This is what I get when plotting the `hc5n_moment` cube (similar is in the moment map).
b18_hc5n_voronoi

I'll look into this later... it looks nice! I do wonder what to do to make the Voronoi cells with less holes

**Comment by low-sky** [comment]
@jpinedaf -- I took a look at B18 and it seems to be working okay at the core level.  However, the gist wasn't up-to-date with the call signatures and I've updated that accordingly.

okay
Here's a stacked spectrum in the resulting cube.
stacked

I note that moment method does accept the axis as a second argument so `moment(0,0)` is fine, but bad form to switch conventions.  If you're not seeing a stacked cube using the up-to-date gist, then maybe we're running into some deviations in the underlying packages.

**Comment by jpinedaf** [comment]
yep, the latest gist does produce the right cube... great!
This is a first attempt to address #58... and it is awesome!

**Pull request merged**
